name: Free Code Review (SwiftLint)

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  SwiftLint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: SwiftLint
        uses: realm/swiftlint@v1
        with:
          version: 'latest'
          # This will automatically post annotations to the PR
          executable: /usr/local/bin/swiftlint
          reporter: 'github-actions-log'
        env:
          DIFF_BASE: ${{ github.base_ref }}
