name: Free Code Review (SwiftLint)

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  SwiftLint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run SwiftLint
        run: swiftlint --reporter github-actions-log
